; generated by PrusaSlicer 2.9.6 on 2026-09-08 at 23:10:02 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.70mm

M104 S200 ; set temperature
;TYPE:Custom
G28 ; home all axes
G1 Z5 F5000 ; lift nozzle
M109 S200 ; set temperature and wait for it to be reached
G21 ; set units to millimeters
G90 ; use absolute coordinates
M82 ; use absolute distances for extrusion
G92 E0
; Filament gcode
M107
;LAYER_CHANGE
;Z:0.35
;HEIGHT:0.35
G1 E-2 F2400
G92 E0
G1 Z.35 F7800
G1 X-1.517 Y-5.924
G1 E2 F2400
;TYPE:Skirt/Brim
;WIDTH:0.7
G1 F1800
G1 X0 Y-6.312 E2.14238
G1 X10 Y-6.312 E3.05168
G1 X12.203 Y-5.916 E3.25521
G1 X14.129 Y-4.775 E3.45877
G1 X15.535 Y-3.034 E3.66226
G1 X16.312 Y0 E3.94704
G1 X16.312 Y10 E4.85634
G1 X15.916 Y12.203 E5.05987
G1 X14.775 Y14.129 E5.26343
G1 X13.034 Y15.535 E5.46692
G1 X10 Y16.312 E5.7517
G1 X0 Y16.312 E6.661
G1 X-2.203 Y15.916 E6.86453
G1 X-4.129 Y14.775 E7.06809
G1 X-5.535 Y13.034 E7.27158
G1 X-6.312 Y10 E7.55636
G1 X-6.312 Y0 E8.46566
G1 X-5.916 Y-2.203 E8.66919
G1 X-4.775 Y-4.129 E8.87275
G1 X-3.034 Y-5.535 E9.07624
G1 X-1.575 Y-5.909 E9.2132
G1 E7.2132 F2400
G92 E0
G92 E0
G1 X8.4 Y8.4 F7800
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:0.7
G1 F1800
G1 X1.6 Y8.4 E2.61832
G1 X1.6 Y1.6 E3.23664
G1 X8.4 Y1.6 E3.85496
G1 X8.4 Y8.34 E4.46782
G1 X9.025 Y9.025 F7800
G1 F1800
G1 X.975 Y9.025 E5.1998
G1 X.975 Y.975 E5.93178
G1 X9.025 Y.975 E6.66376
G1 X9.025 Y8.965 E7.39029
G1 X9.65 Y9.65 F7800
;TYPE:External perimeter
G1 F1800
G1 X.35 Y9.65 E8.23593
G1 X.35 Y.35 E9.08157
G1 X9.65 Y.35 E9.92721
G1 X9.65 Y9.59 E10.7674
G1 X9.254 Y9.649 F7800
G1 E8.7674 F2400
G92 E0
G1 X6.885 Y1.787 F7800
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:0.730498
G1 F1800
G1 X7.932 Y2.834 E2.14121
G1 X7.932 Y3.761 E2.22962
G1 X6.239 Y2.068 E2.45795
G1 X5.312 Y2.068 E2.54636
G1 X7.932 Y4.688 E2.89972
G1 X7.932 Y5.614 E2.98803
G1 X4.386 Y2.068 E3.46628
G1 X3.459 Y2.068 E3.55469
G1 X7.932 Y6.541 E4.15796
G1 X7.932 Y7.468 E4.24637
G1 X2.532 Y2.068 E4.97467
G1 X2.068 Y2.068 E5.01892
G1 X2.068 Y2.532 E5.06317
G1 X7.468 Y7.932 E5.79147
G1 X6.541 Y7.932 E5.87988
G1 X2.068 Y3.459 E6.48315
G1 X2.068 Y4.386 E6.57156
G1 X5.614 Y7.932 E7.04981
G1 X4.687 Y7.932 E7.13822
G1 X2.068 Y5.313 E7.49144
G1 X2.068 Y6.239 E7.57975
G1 X3.761 Y7.932 E7.80808
G1 X2.834 Y7.932 E7.89649
G1 X1.787 Y6.885 E8.0377
;LAYER_CHANGE
;Z:0.65
;HEIGHT:0.3
G1 E6.0377 F2400
G92 E0
G1 Z.65 F7800
G1 X9.004 Y9.004
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X.996 Y9.004 E2.38516
G1 X.996 Y.996 E2.77032
G1 X9.004 Y.996 E3.15548
G1 X9.004 Y8.944 E3.53775
G1 X9.389 Y9.389 F7800
G1 F900
G1 X.611 Y9.389 E3.95994
G1 X.611 Y.611 E4.38213
G1 X9.389 Y.611 E4.80432
G1 X9.389 Y9.329 E5.22363
G1 X9.775 Y9.775 F7800
;TYPE:External perimeter
G1 F900
G1 X.225 Y9.775 E5.68295
G1 X.225 Y.225 E6.14227
G1 X9.775 Y.225 E6.60159
G1 X9.775 Y9.715 E7.05803
G1 X9.379 Y9.774 F7800
G1 E5.05803 F2400
G92 E0
G1 X1.39 Y1.317 F7800
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:0.543559
G1 F1200
G1 X1.348 Y1.274 E2.00359
G1 X1.29 Y1.29 E2.00719
G1 X1.274 Y1.348 E2.01079
G1 X1.317 Y1.39 E2.01438
G1 X1.375 Y1.375 E2.01796
;WIDTH:0.45
G1 X1.991 Y1.285 E2.0479
G1 X1.162 Y2.128 E2.10477
;WIDTH:0.404381
G1 X1.091 Y2.109 E2.10789
G1 X1.11 Y2.18 E2.11101
G1 X1.151 Y2.169 E2.11281
;WIDTH:0.45
G1 X1.285 Y2.536 E2.1316
G1 X2.536 Y1.285 E2.21669
G1 X3.081 Y1.285 E2.2429
G1 X1.285 Y3.081 E2.36506
G1 X1.285 Y3.627 E2.39132
G1 X3.627 Y1.285 E2.55062
G1 X4.172 Y1.285 E2.57683
G1 X1.285 Y4.172 E2.7732
G1 X1.285 Y4.717 E2.79941
G1 X4.717 Y1.285 E3.03285
G1 X5.263 Y1.285 E3.05911
G1 X1.285 Y5.263 E3.32969
G1 X1.285 Y5.808 E3.3559
G1 X5.808 Y1.285 E3.66355
G1 X6.353 Y1.285 E3.68976
G1 X1.285 Y6.353 E4.03448
G1 X1.285 Y6.899 E4.06074
G1 X6.899 Y1.285 E4.4426
G1 X7.444 Y1.285 E4.46881
G1 X1.285 Y7.444 E4.88774
G1 X1.285 Y7.989 E4.91395
G1 X7.989 Y1.285 E5.36995
G1 X8.535 Y1.285 E5.39621
G1 X1.285 Y8.535 E5.88935
G1 X1.224 Y8.836 E5.90412
;WIDTH:0.404381
G1 X1.183 Y8.847 E5.90592
G1 X1.164 Y8.776 E5.90904
G1 X1.235 Y8.795 E5.91216
;WIDTH:0.45
G1 X1.651 Y8.715 E5.93253
G1 X8.715 Y1.651 E6.41301
G1 X8.715 Y2.196 E6.43922
G1 X2.196 Y8.715 E6.88263
G1 X2.742 Y8.715 E6.90889
G1 X8.715 Y2.742 E7.31517
G1 X8.715 Y3.287 E7.34138
G1 X3.287 Y8.715 E7.71059
G1 X3.832 Y8.715 E7.7368
G1 X8.715 Y3.832 E8.06894
G1 X8.715 Y4.378 E8.0952
G1 X4.378 Y8.715 E8.3902
G1 X4.923 Y8.715 E8.41641
G1 X8.715 Y4.923 E8.67434
G1 X8.715 Y5.468 E8.70055
G1 X5.468 Y8.715 E8.92141
G1 X6.014 Y8.715 E8.94767
G1 X8.715 Y6.014 E9.13139
G1 X8.92 Y6.4 E9.15241
;WIDTH:0.404381
G1 X8.849 Y6.381 E9.15553
G1 X8.868 Y6.452 E9.15865
G1 X8.909 Y6.441 E9.16045
;WIDTH:0.45
G1 X8.715 Y6.559 E9.17137
G1 X6.559 Y8.715 E9.31802
G1 X6.452 Y8.868 E9.327
;WIDTH:0.404381
G1 X6.381 Y8.849 E9.33012
G1 X6.4 Y8.92 E9.33324
G1 X6.441 Y8.909 E9.33504
G1 E7.33504 F2400
G92 E0
G1 X8.578 Y7.241 F7800
G1 E2 F2400
;WIDTH:0.45
G1 F1200
G1 X7.104 Y8.715 E2.10026
G1 X8.715 Y8.715 E2.17774
G1 X8.715 Y7.104 E2.25522
G1 X8.31 Y8.225 F7800
;WIDTH:0.621939
G1 F1200
G1 X8.261 Y8.176 E2.26004
G1 X8.194 Y8.194 E2.26486
G1 X8.176 Y8.261 E2.26968
G1 X8.225 Y8.31 E2.2745
G1 X8.292 Y8.292 E2.27932
;LAYER_CHANGE
;Z:0.95
;HEIGHT:0.3
G1 Z.95 F7800
G1 X9.004 Y9.004
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X.996 Y9.004 E2.66448
G1 X.996 Y.996 E3.04964
G1 X9.004 Y.996 E3.4348
G1 X9.004 Y8.944 E3.81707
G1 X9.389 Y9.389 F7800
G1 F900
G1 X.611 Y9.389 E4.23926
G1 X.611 Y.611 E4.66145
G1 X9.389 Y.611 E5.08364
G1 X9.389 Y9.329 E5.50295
G1 X9.775 Y9.775 F7800
;TYPE:External perimeter
G1 F900
G1 X.225 Y9.775 E5.96227
G1 X.225 Y.225 E6.42159
G1 X9.775 Y.225 E6.88091
G1 X9.775 Y9.715 E7.33735
G1 X9.379 Y9.774 F7800
G1 E5.33735 F2400
G92 E0
G1 X1.317 Y8.61 F7800
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:0.543559
G1 F1200
G1 X1.274 Y8.652 E2.00359
G1 X1.29 Y8.71 E2.00719
G1 X1.348 Y8.726 E2.01079
G1 X1.39 Y8.683 E2.01438
G1 X1.375 Y8.625 E2.01796
;WIDTH:0.45
G1 X1.285 Y8.009 E2.0479
G1 X1.991 Y8.715 E2.09592
G1 X2.536 Y8.715 E2.12213
G1 X1.285 Y7.464 E2.20722
G1 X1.285 Y6.919 E2.23343
G1 X3.081 Y8.715 E2.35559
G1 X3.627 Y8.715 E2.38185
G1 X1.285 Y6.373 E2.54115
G1 X1.285 Y5.828 E2.56736
G1 X4.172 Y8.715 E2.76373
G1 X4.717 Y8.715 E2.78994
G1 X1.285 Y5.283 E3.02338
G1 X1.285 Y4.737 E3.04964
G1 X5.263 Y8.715 E3.32022
G1 X5.808 Y8.715 E3.34643
G1 X1.285 Y4.192 E3.65408
G1 X1.285 Y3.647 E3.68029
G1 X6.353 Y8.715 E4.02501
G1 X6.899 Y8.715 E4.05127
G1 X1.285 Y3.101 E4.43313
G1 X1.285 Y2.556 E4.45934
G1 X7.444 Y8.715 E4.87827
G1 X7.989 Y8.715 E4.90448
G1 X1.285 Y2.011 E5.36048
G1 X1.285 Y1.465 E5.38674
G1 X8.535 Y8.715 E5.87988
G1 X8.795 Y8.765 E5.89261
;WIDTH:0.404381
G1 X8.776 Y8.836 E5.89573
G1 X8.847 Y8.817 E5.89885
G1 X8.836 Y8.776 E5.90065
;WIDTH:0.45
G1 X8.715 Y8.349 E5.922
G1 X1.651 Y1.285 E6.40248
G1 X2.196 Y1.285 E6.42869
G1 X8.715 Y7.804 E6.8721
G1 X8.715 Y7.258 E6.89836
G1 X2.742 Y1.285 E7.30464
G1 X3.287 Y1.285 E7.33085
G1 X8.715 Y6.713 E7.70006
G1 X8.715 Y6.168 E7.72627
G1 X3.832 Y1.285 E8.05841
G1 X4.378 Y1.285 E8.08467
G1 X8.715 Y5.622 E8.37967
G1 X8.715 Y5.077 E8.40588
G1 X4.923 Y1.285 E8.66381
G1 X5.468 Y1.285 E8.69002
G1 X8.715 Y4.532 E8.91088
G1 X8.715 Y3.986 E8.93714
G1 X6.014 Y1.285 E9.12086
G1 X6.4 Y1.08 E9.14188
;WIDTH:0.404381
G1 X6.381 Y1.151 E9.145
G1 X6.452 Y1.132 E9.14812
G1 X6.441 Y1.091 E9.14992
;WIDTH:0.45
G1 X6.559 Y1.285 E9.16084
G1 X8.715 Y3.441 E9.30749
G1 X8.909 Y3.559 E9.31841
;WIDTH:0.404381
G1 X8.92 Y3.6 E9.32021
G1 X8.849 Y3.619 E9.32333
G1 X8.868 Y3.548 E9.32645
G1 E7.32645 F2400
G92 E0
G1 X7.241 Y1.422 F7800
G1 E2 F2400
;WIDTH:0.45
G1 F1200
G1 X8.715 Y2.896 E2.10026
G1 X8.715 Y1.285 E2.17774
G1 X7.104 Y1.285 E2.25522
G1 X8.225 Y1.69 F7800
;WIDTH:0.621937
G1 F1200
G1 X8.176 Y1.739 E2.26004
G1 X8.194 Y1.806 E2.26486
G1 X8.261 Y1.824 E2.26968
G1 X8.31 Y1.775 E2.2745
G1 X8.292 Y1.708 E2.27932
M106 S221.85
;LAYER_CHANGE
;Z:1.25
;HEIGHT:0.3
G1 E.27932 F2400
G92 E0
G1 Z1.25 F7800
G1 X9.004 Y9.004
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X.996 Y9.004 E2.38516
G1 X.996 Y.996 E2.77032
G1 X9.004 Y.996 E3.15548
G1 X9.004 Y8.944 E3.53775
G1 X9.389 Y9.389 F7800
G1 F900
G1 X.611 Y9.389 E3.95994
G1 X.611 Y.611 E4.38213
G1 X9.389 Y.611 E4.80432
G1 X9.389 Y9.329 E5.22363
G1 X9.775 Y9.775 F7800
;TYPE:External perimeter
G1 F900
G1 X.225 Y9.775 E5.68295
G1 X.225 Y.225 E6.14227
G1 X9.775 Y.225 E6.60159
G1 X9.775 Y9.715 E7.05803
G1 X9.379 Y9.774 F7800
G1 E5.05803 F2400
G92 E0
G1 X1.39 Y1.317 F7800
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:0.543559
G1 F1200
G1 X1.348 Y1.274 E2.00359
G1 X1.29 Y1.29 E2.00719
G1 X1.274 Y1.348 E2.01079
G1 X1.317 Y1.39 E2.01438
G1 X1.375 Y1.375 E2.01796
;WIDTH:0.45
G1 X1.991 Y1.285 E2.0479
G1 X1.162 Y2.128 E2.10477
;WIDTH:0.404381
G1 X1.091 Y2.109 E2.10789
G1 X1.11 Y2.18 E2.11101
G1 X1.151 Y2.169 E2.11281
;WIDTH:0.45
G1 X1.285 Y2.536 E2.1316
G1 X2.536 Y1.285 E2.21669
G1 X3.081 Y1.285 E2.2429
G1 X1.285 Y3.081 E2.36506
G1 X1.285 Y3.627 E2.39132
G1 X3.627 Y1.285 E2.55062
G1 X4.172 Y1.285 E2.57683
G1 X1.285 Y4.172 E2.7732
G1 X1.285 Y4.717 E2.79941
G1 X4.717 Y1.285 E3.03285
G1 X5.263 Y1.285 E3.05911
G1 X1.285 Y5.263 E3.32969
G1 X1.285 Y5.808 E3.3559
G1 X5.808 Y1.285 E3.66355
G1 X6.353 Y1.285 E3.68976
G1 X1.285 Y6.353 E4.03448
G1 X1.285 Y6.899 E4.06074
G1 X6.899 Y1.285 E4.4426
G1 X7.444 Y1.285 E4.46881
G1 X1.285 Y7.444 E4.88774
G1 X1.285 Y7.989 E4.91395
G1 X7.989 Y1.285 E5.36995
G1 X8.535 Y1.285 E5.39621
G1 X1.285 Y8.535 E5.88935
G1 X1.224 Y8.836 E5.90412
;WIDTH:0.404381
G1 X1.183 Y8.847 E5.90592
G1 X1.164 Y8.776 E5.90904
G1 X1.235 Y8.795 E5.91216
;WIDTH:0.45
G1 X1.651 Y8.715 E5.93253
G1 X8.715 Y1.651 E6.41301
G1 X8.715 Y2.196 E6.43922
G1 X2.196 Y8.715 E6.88263
G1 X2.742 Y8.715 E6.90889
G1 X8.715 Y2.742 E7.31517
G1 X8.715 Y3.287 E7.34138
G1 X3.287 Y8.715 E7.71059
G1 X3.832 Y8.715 E7.7368
G1 X8.715 Y3.832 E8.06894
G1 X8.715 Y4.378 E8.0952
G1 X4.378 Y8.715 E8.3902
G1 X4.923 Y8.715 E8.41641
G1 X8.715 Y4.923 E8.67434
G1 X8.715 Y5.468 E8.70055
G1 X5.468 Y8.715 E8.92141
G1 X6.014 Y8.715 E8.94767
G1 X8.715 Y6.014 E9.13139
G1 X8.92 Y6.4 E9.15241
;WIDTH:0.404381
G1 X8.849 Y6.381 E9.15553
G1 X8.868 Y6.452 E9.15865
G1 X8.909 Y6.441 E9.16045
;WIDTH:0.45
G1 X8.715 Y6.559 E9.17137
G1 X6.559 Y8.715 E9.31802
G1 X6.452 Y8.868 E9.327
;WIDTH:0.404381
G1 X6.381 Y8.849 E9.33012
G1 X6.4 Y8.92 E9.33324
G1 X6.441 Y8.909 E9.33504
G1 E7.33504 F2400
G92 E0
G1 X8.578 Y7.241 F7800
G1 E2 F2400
;WIDTH:0.45
G1 F1200
G1 X7.104 Y8.715 E2.10026
G1 X8.715 Y8.715 E2.17774
G1 X8.715 Y7.104 E2.25522
G1 X8.31 Y8.225 F7800
;WIDTH:0.621939
G1 F1200
G1 X8.261 Y8.176 E2.26004
G1 X8.194 Y8.194 E2.26486
G1 X8.176 Y8.261 E2.26968
G1 X8.225 Y8.31 E2.2745
G1 X8.292 Y8.292 E2.27932
;LAYER_CHANGE
;Z:1.55
;HEIGHT:0.3
G1 Z1.55 F7800
G1 X9.004 Y9.004
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X.996 Y9.004 E2.66448
G1 X.996 Y.996 E3.04964
G1 X9.004 Y.996 E3.4348
G1 X9.004 Y8.944 E3.81707
G1 X9.389 Y9.389 F7800
G1 F900
G1 X.611 Y9.389 E4.23926
G1 X.611 Y.611 E4.66145
G1 X9.389 Y.611 E5.08364
G1 X9.389 Y9.329 E5.50295
G1 X9.775 Y9.775 F7800
;TYPE:External perimeter
G1 F900
G1 X.225 Y9.775 E5.96227
G1 X.225 Y.225 E6.42159
G1 X9.775 Y.225 E6.88091
G1 X9.775 Y9.715 E7.33735
G1 X9.379 Y9.774 F7800
G1 E5.33735 F2400
G92 E0
G1 X1.317 Y8.61 F7800
G1 E2 F2400
;TYPE:Solid infill
;WIDTH:0.543559
G1 F1200
G1 X1.274 Y8.652 E2.00359
G1 X1.29 Y8.71 E2.00719
G1 X1.348 Y8.726 E2.01079
G1 X1.39 Y8.683 E2.01438
G1 X1.375 Y8.625 E2.01796
;WIDTH:0.45
G1 X1.285 Y8.009 E2.0479
G1 X1.991 Y8.715 E2.09592
G1 X2.536 Y8.715 E2.12213
G1 X1.285 Y7.464 E2.20722
G1 X1.285 Y6.919 E2.23343
G1 X3.081 Y8.715 E2.35559
G1 X3.627 Y8.715 E2.38185
G1 X1.285 Y6.373 E2.54115
G1 X1.285 Y5.828 E2.56736
G1 X4.172 Y8.715 E2.76373
G1 X4.717 Y8.715 E2.78994
G1 X1.285 Y5.283 E3.02338
G1 X1.285 Y4.737 E3.04964
G1 X5.263 Y8.715 E3.32022
G1 X5.808 Y8.715 E3.34643
G1 X1.285 Y4.192 E3.65408
G1 X1.285 Y3.647 E3.68029
G1 X6.353 Y8.715 E4.02501
G1 X6.899 Y8.715 E4.05127
G1 X1.285 Y3.101 E4.43313
G1 X1.285 Y2.556 E4.45934
G1 X7.444 Y8.715 E4.87827
G1 X7.989 Y8.715 E4.90448
G1 X1.285 Y2.011 E5.36048
G1 X1.285 Y1.465 E5.38674
G1 X8.535 Y8.715 E5.87988
G1 X8.795 Y8.765 E5.89261
;WIDTH:0.404381
G1 X8.776 Y8.836 E5.89573
G1 X8.847 Y8.817 E5.89885
G1 X8.836 Y8.776 E5.90065
;WIDTH:0.45
G1 X8.715 Y8.349 E5.922
G1 X1.651 Y1.285 E6.40248
G1 X2.196 Y1.285 E6.42869
G1 X8.715 Y7.804 E6.8721
G1 X8.715 Y7.258 E6.89836
G1 X2.742 Y1.285 E7.30464
G1 X3.287 Y1.285 E7.33085
G1 X8.715 Y6.713 E7.70006
G1 X8.715 Y6.168 E7.72627
G1 X3.832 Y1.285 E8.05841
G1 X4.378 Y1.285 E8.08467
G1 X8.715 Y5.622 E8.37967
G1 X8.715 Y5.077 E8.40588
G1 X4.923 Y1.285 E8.66381
G1 X5.468 Y1.285 E8.69002
G1 X8.715 Y4.532 E8.91088
G1 X8.715 Y3.986 E8.93714
G1 X6.014 Y1.285 E9.12086
G1 X6.4 Y1.08 E9.14188
;WIDTH:0.404381
G1 X6.381 Y1.151 E9.145
G1 X6.452 Y1.132 E9.14812
G1 X6.441 Y1.091 E9.14992
;WIDTH:0.45
G1 X6.559 Y1.285 E9.16084
G1 X8.715 Y3.441 E9.30749
G1 X8.909 Y3.559 E9.31841
;WIDTH:0.404381
G1 X8.92 Y3.6 E9.32021
G1 X8.849 Y3.619 E9.32333
G1 X8.868 Y3.548 E9.32645
G1 E7.32645 F2400
G92 E0
G1 X7.241 Y1.422 F7800
G1 E2 F2400
;WIDTH:0.45
G1 F1200
G1 X8.715 Y2.896 E2.10026
G1 X8.715 Y1.285 E2.17774
G1 X7.104 Y1.285 E2.25522
G1 X8.225 Y1.69 F7800
;WIDTH:0.621937
G1 F1200
G1 X8.176 Y1.739 E2.26004
G1 X8.194 Y1.806 E2.26486
G1 X8.261 Y1.824 E2.26968
G1 X8.31 Y1.775 E2.2745
G1 X8.292 Y1.708 E2.27932
M106 S211.65
;LAYER_CHANGE
;Z:1.85
;HEIGHT:0.3
G1 E.27932 F2400
G92 E0
G1 Z1.85 F7800
G1 X9.004 Y9.004
G1 E2 F2400
;TYPE:Perimeter
;WIDTH:0.45
G1 F900
G1 X.996 Y9.004 E2.38516
G1 X.996 Y.996 E2.77032
G1 X9.004 Y.996 E3.15548
G1 X9.004 Y8.944 E3.53775
G1 X9.389 Y9.389 F7800
G1 F900
G1 X.611 Y9.389 E3.95994
G1 X.611 Y.611 E4.38213
G1 X9.389 Y.611 E4.80432
G1 X9.389 Y9.329 E5.22363
G1 X9.775 Y9.775 F7800
;TYPE:External perimeter
G1 F900
G1 X.225 Y9.775 E5.68295
G1 X.225 Y.225 E6.14227
G1 X9.775 Y.225 E6.60159
G1 X9.775 Y9.715 E7.05803
G1 X9.379 Y9.774 F7800
G1 X8.891 Y8.191
;TYPE:Top solid infill
;WIDTH:0.409745
G1 F900
G1 X8.342 Y8.74 E7.09147
G1 X7.854 Y8.74 E7.11249
G1 X8.74 Y7.854 E7.16646
G1 X8.74 Y7.366 E7.18748
G1 X7.366 Y8.74 E7.27118
G1 X6.877 Y8.74 E7.29224
G1 X8.74 Y6.877 E7.40573
G1 X8.74 Y6.389 E7.42675
G1 X6.389 Y8.74 E7.56997
G1 X5.9 Y8.74 E7.59103
G1 X8.74 Y5.9 E7.76404
G1 X8.74 Y5.412 E7.78506
G1 X5.412 Y8.74 E7.9878
G1 X4.924 Y8.74 E8.00882
G1 X8.74 Y4.924 E8.24128
G1 X8.74 Y4.435 E8.26234
G1 X4.435 Y8.74 E8.52459
G1 X3.947 Y8.74 E8.54561
G1 X8.74 Y3.947 E8.83759
G1 X8.74 Y3.458 E8.85865
G1 X3.458 Y8.74 E9.18042
G1 X2.97 Y8.74 E9.20144
G1 X8.74 Y2.97 E9.55294
G1 X8.74 Y2.481 E9.574
G1 X2.481 Y8.74 E9.95529
G1 X1.993 Y8.74 E9.97631
G1 X8.74 Y1.993 E10.38733
G1 X8.74 Y1.505 E10.40835
G1 X1.505 Y8.74 E10.84909
G1 X1.26 Y8.74 E10.85964
G1 X1.26 Y8.495 E10.87019
G1 X8.495 Y1.26 E11.31093
G1 X8.007 Y1.26 E11.33195
G1 X1.26 Y8.007 E11.74297
G1 X1.26 Y7.518 E11.76403
G1 X7.518 Y1.26 E12.14526
G1 X7.03 Y1.26 E12.16628
G1 X1.26 Y7.03 E12.51778
G1 X1.26 Y6.542 E12.5388
G1 X6.542 Y1.26 E12.86057
G1 X6.053 Y1.26 E12.88163
G1 X1.26 Y6.053 E13.17361
G1 X1.26 Y5.565 E13.19463
G1 X5.565 Y1.26 E13.45688
G1 X5.076 Y1.26 E13.47794
G1 X1.26 Y5.076 E13.7104
G1 X1.26 Y4.588 E13.73142
G1 X4.588 Y1.26 E13.93416
G1 X4.1 Y1.26 E13.95518
G1 X1.26 Y4.1 E14.12819
G1 X1.26 Y3.611 E14.14925
G1 X3.611 Y1.26 E14.29247
G1 X3.123 Y1.26 E14.31349
G1 X1.26 Y3.123 E14.42698
G1 X1.26 Y2.634 E14.44804
G1 X2.634 Y1.26 E14.53174
G1 X2.146 Y1.26 E14.55276
G1 X1.26 Y2.146 E14.60673
G1 X1.26 Y1.657 E14.62779
G1 X1.808 Y1.109 E14.66117
G1 E12.66117 F2400
G92 E0
M107
;TYPE:Custom
; Filament-specific end gcode 
;END gcode for filament
M104 S0 ; turn off temperature
G28 X0  ; home X axis
M84     ; disable motors
; objects_info = {"objects":[]}
; filament used [mm] = 85.35
; filament used [cm3] = 0.21
; total filament used [g] = 0.00
; total filament cost = 0.00
; total filament used for wipe tower [g] = 0.00
; estimated printing time (normal mode) = 1m 33s
; estimated first layer printing time (normal mode) = 10s

; prusaslicer_config = begin
; arc_fitting = disabled
; autoemit_temperature_commands = 1
; automatic_extrusion_widths = 0
; automatic_infill_combination = 0
; automatic_infill_combination_max_layer_height = 100%
; avoid_crossing_curled_overhangs = 0
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_shape = 0x0,200x0,200x200,0x200
; bed_temperature = 0
; bed_temperature_extruder = 0
; before_layer_gcode = 
; between_objects_gcode = 
; binary_gcode = 0
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 3
; bottom_solid_min_thickness = 0
; bridge_acceleration = 0
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 1
; bridge_speed = 60
; brim_separation = 0
; brim_type = outer_only
; brim_width = 0
; chamber_minimal_temperature = 0
; chamber_temperature = 0
; color_change_gcode = M600
; colorprint_heights = 
; complete_objects = 0
; cooling = 1
; cooling_perimeter_transition_distance = 0
; cooling_slowdown_logic = uniform_cooling
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; custom_parameters_filament = ""
; custom_parameters_print = 
; custom_parameters_printer = 
; default_acceleration = 0
; deretract_speed = 0
; disable_fan_first_layers = 3
; dont_support_bridges = 1
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0
; enable_dynamic_fan_speeds = 0
; enable_dynamic_overhang_speeds = 0
; end_filament_gcode = "; Filament-specific end gcode \n;END gcode for filament\n"
; end_gcode = M104 S0 ; turn off temperature\nG28 X0  ; home X axis\nM84     ; disable motors\n
; ensure_vertical_shell_thickness = enabled
; external_perimeter_acceleration = 0
; external_perimeter_extrusion_width = 0
; external_perimeter_speed = 50%
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 1
; extra_perimeters_on_overhangs = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 20
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 1
; extrusion_width = 0
; fan_always_on = 0
; fan_below_layer_time = 60
; filament_abrasive = 0
; filament_colour = #29B2B2
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 0
; filament_density = 0
; filament_diameter = 1.75
; filament_flush_speed = 0
; filament_flush_volume = 0
; filament_infill_max_crossing_speed = 0
; filament_infill_max_speed = 0
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 0
; filament_minimal_purge_on_wipe_tower = 15
; filament_multitool_ramming = 0
; filament_multitool_ramming_flow = 10
; filament_multitool_ramming_volume = 10
; filament_notes = ""
; filament_purge_multiplier = 100%
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_seam_gap_distance = 15%
; filament_settings_id = ""
; filament_shrinkage_compensation_xy = 0%
; filament_shrinkage_compensation_z = 0%
; filament_soluble = 0
; filament_spool_weight = 0
; filament_stamping_distance = 0
; filament_stamping_loading_speed = 20
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; fill_angle = 45
; fill_density = 20%
; fill_pattern = stars
; first_layer_acceleration = 0
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 0
; first_layer_extrusion_width = 200%
; first_layer_height = 0.35
; first_layer_infill_speed = 0
; first_layer_speed = 30
; first_layer_speed_over_raft = 30
; first_layer_temperature = 200
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 20
; gcode_comments = 0
; gcode_flavor = reprap
; gcode_label_objects = disabled
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; idle_temperature = nil
; infill_acceleration = 0
; infill_anchor = 600%
; infill_anchor_max = 50
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0
; infill_first = 0
; infill_overlap = 25%
; infill_speed = 80
; interface_shells = 0
; interlocking_beam = 0
; interlocking_beam_layer_count = 2
; interlocking_beam_width = 0.8
; interlocking_boundary_avoidance = 2
; interlocking_depth = 2
; interlocking_orientation = 22.5
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = 
; layer_height = 0.3
; machine_limits_usage = time_estimate_only
; machine_max_acceleration_e = 10000,5000
; machine_max_acceleration_extruding = 1500,1250
; machine_max_acceleration_retracting = 1500,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 9000,1000
; machine_max_acceleration_y = 9000,1000
; machine_max_acceleration_z = 500,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 500,200
; machine_max_feedrate_y = 500,200
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 2.5,2.5
; machine_max_jerk_x = 10,10
; machine_max_jerk_y = 10,10
; machine_max_jerk_z = 0.2,0.4
; machine_max_junction_deviation = 0,0
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 100
; max_layer_height = 0
; max_print_height = 200
; max_print_speed = 80
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 35
; min_feature_size = 25%
; min_layer_height = 0.07
; min_print_speed = 10
; min_skirt_length = 0
; mmu_segmented_region_interlocking_depth = 0
; mmu_segmented_region_max_width = 0
; multimaterial_purging = 140
; notes = 
; nozzle_diameter = 0.4
; nozzle_high_flow = 0
; only_one_perimeter_first_layer = 0
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = [input_filename_base].gcode
; over_bridge_speed = 0
; overhang_fan_speed_0 = 0
; overhang_fan_speed_1 = 0
; overhang_fan_speed_2 = 0
; overhang_fan_speed_3 = 0
; overhang_speed_0 = 15
; overhang_speed_1 = 15
; overhang_speed_2 = 20
; overhang_speed_3 = 25
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 0
; perimeter_extruder = 1
; perimeter_extrusion_width = 0
; perimeter_generator = arachne
; perimeter_speed = 60
; perimeters = 3
; physical_printer_settings_id = 
; post_process = 
; prefer_clockwise_movements = 0
; print_settings_id = 
; printer_model = 
; printer_notes = 
; printer_settings_id = 
; printer_technology = FFF
; raft_contact_distance = 0.1
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 0
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 0%
; retract_layer_change = 0
; retract_length = 2
; retract_length_toolchange = 10
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 0
; retract_restart_extra = 0
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; scarf_seam_entire_loop = 0
; scarf_seam_length = 20
; scarf_seam_max_segment_length = 1
; scarf_seam_on_inner_perimeters = 0
; scarf_seam_only_on_smooth = 1
; scarf_seam_placement = nowhere
; scarf_seam_start_height = 0%
; seam_gap_distance = 15%
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 1
; skirt_distance = 6
; skirt_height = 1
; skirts = 1
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 5
; small_perimeter_speed = 15
; solid_infill_acceleration = 0
; solid_infill_below_area = 70
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0
; solid_infill_speed = 20
; spiral_vase = 0
; staggered_inner_seams = 0
; standby_temperature_delta = -5
; start_filament_gcode = "; Filament gcode\n"
; start_gcode = G28 ; home all axes\nG1 Z5 F5000 ; lift nozzle\n
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = -1
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 1
; support_material_extrusion_width = 0
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 1
; support_material_interface_layers = 3
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0
; support_material_interface_speed = 100%
; support_material_pattern = rectilinear
; support_material_spacing = 2.5
; support_material_speed = 60
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 0
; support_material_with_sheath = 1
; support_material_xy_spacing = 50%
; support_tree_angle = 40
; support_tree_angle_slow = 25
; support_tree_branch_diameter = 2
; support_tree_branch_diameter_angle = 5
; support_tree_branch_diameter_double_wall = 3
; support_tree_branch_distance = 1
; support_tree_tip_diameter = 0.8
; support_tree_top_rate = 15%
; temperature = 200
; template_custom_gcode = 
; thick_bridges = 1
; thin_walls = 1
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; toolchange_ordering = optimized
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0
; top_one_perimeter_type = none
; top_solid_infill_acceleration = 0
; top_solid_infill_speed = 15
; top_solid_layers = 3
; top_solid_min_thickness = 0
; travel_acceleration = 0
; travel_lift_before_obstacle = 0
; travel_max_lift = 0
; travel_ramping_lift = 0
; travel_short_distance_acceleration = 0
; travel_slope = 0
; travel_speed = 130
; travel_speed_z = 0
; use_firmware_retraction = 0
; use_relative_e_distances = 0
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 100%
; wipe = 0
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 0
; wipe_tower_acceleration = 0
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_cone_angle = 0
; wipe_tower_extra_flow = 100%
; wipe_tower_extra_spacing = 100%
; wipe_tower_extruder = 0
; wipe_tower_no_sparse_layers = 0
; wipe_tower_width = 60
; wiping_volumes_matrix = 0,140,140,140,140,140,0,140,140,140,140,140,0,140,140,140,140,140,0,140,140,140,140,140,0
; wiping_volumes_use_custom_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
